version: "3.3"
services:
   springwebapp:
       image: 10.0.2.15:8083/springboot:45
       restart: always
       container_name: springcontainer
       ports:
       - 8086:8080
       networks:
       - springappnetwork
       depends_on:
       - mongo        
       environment:
       - MONGO_DB_HOSTNAME=mongo
       - MONGO_DB_USERNAME=devdb
       - MONGO_DB_PASSWORD=devdb1234
       working_dir: /opt/app
   mongo:
       image: mongo
       restart: always
       container_name: mongocontainer
       networks:
       - springappnetwork
       environment:
       - MONGO_INITDB_ROOT_USERNAME=devdb
       - MONGO_INITDB_ROOT_PASSWORD=devdb1234
       volumes:
       - mongovol:/data/db
volumes:
       mongovol:
        external: true
networks:
       springappnetwork:
        external: true
       
